[package]
name = "widget_host"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "=1.10", default-features = false, features = [
    "v5",
    "serde",
] }
thing_abi = { path = "../../thing_abi" }
widget_launcher_entry = { path = "../widget_launcher_entry" }
widget_scrollbar_thumb = { path = "../widget_scrollbar_thumb" }
widget_toolbar = { path = "../widget_toolbar" }
widget_toolbar_button = { path = "../widget_toolbar_button" }
widget_listbox_default = { path = "../widget_listbox_default" }

[features]
default = []
std = ["userland/std"]
host = ["std"]

[[bin]]
name = "widget_host"
path = "src/main.rs"
