[package]
name = "graph_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
thing_abi = { path = "../../thing_abi" }
uuid = { version = "1.10.0", default-features = false, features = ["v5"] }
unifont = { version = "1.1.0", default-features = false }

[features]
default = []
std = ["userland/std"]
kernel_hosted = ["userland/kernel_hosted"]
disable_panic_handler = ["userland/disable_panic_handler"]

[[bin]]
name = "graph_viewer"
path = "src/main.rs"
