use thing_abi::{canon, cc, Symbol};

const SYMBOL_TABLE: &[(Symbol, &str)] = &[
    (cc('J', 'N'), "journal"),
    (cc('K', 'B'), "keyboard"),
    (cc('K', 'P'), "key_pressed"),
    (canon(b'K', b'E', b'V'), "key_event"),
    (cc('M', 'S'), "mouse"),
    (cc('M', 'V'), "mouse_moved"),
    (canon(b'M', b'M', b'V'), "mouse_move"),
    (canon(b'M', b'B', b'T'), "mouse_button"),
    (canon(b'I', b'D', b'M'), "input.device.mouse"),
    (canon(b'I', b'E', b'V'), "input.event"),
    (canon(b'M', b'O', b'V'), "move"),
    (canon(b'D', b'I', b'D'), "device_id"),
    (canon(b'T', b'S', b' '), "ts"),
    (canon(b'D', b'W', b'N'), "down"),
    (canon(b'B', b'T', b'#'), "button"),
    (cc('@', ' '), "at"),
    (cc('I', 'N'), "init"),
    (cc('F', 'L'), "fail"),
    (cc('D', 'R'), "driver"),
    (cc('T', 'C'), "thing_created"),
    (cc('E', 'D'), "edge_added"),
    (canon(b'I', b'D', b' '), "id"),
    (canon(b'K', b'N', b'D'), "kind"),
    (canon(b'F', b'L', b'D'), "fields"),
    (canon(b'R', b'V', b'N'), "revision"),
    (canon(b'S', b'R', b'C'), "src"),
    (canon(b'D', b'S', b'T'), "dst"),
    (canon(b'P', b'R', b'D'), "predicate"),
    (canon(b'N', b'A', b'M'), "name"),
    (canon(b'S', b'T', b'A'), "status"),
    (canon(b'S', b'C', b'N'), "scancode"),
    (canon(b'K', b'E', b'Y'), "key"),
    (canon(b'D', b'X', b' '), "dx"),
    (canon(b'D', b'Y', b' '), "dy"),
    (canon(b'B', b'T', b'N'), "buttons"),
    (canon(b'W', b'R', b'T'), "write"),
    (canon(b'B', b'N', b'D'), "bundle"),
    (canon(b'O', b'W', b'N'), "owner"),
    (canon(b'O', b'W', b'S'), "owns"),
    (canon(b'C', b'R', b'D'), "can_read"),
    (canon(b'C', b'W', b'R'), "can_write"),
    (canon(b'C', b'L', b'K'), "can_link"),
    (canon(b'C', b'I', b'Q'), "can_handle_irq"),
    (canon(b'C', b'D', b'M'), "can_dma"),
    (canon(b'C', b'M', b'M'), "can_mmio"),
    (canon(b'C', b'P', b'O'), "can_port_io"),
    (canon(b'T', b'G', b'T'), "target"),
    (canon(b'T', b'X', b'T'), "text"),
    (canon(b'S', b'T', b'D'), "stdout"),
    (canon(b'A', b'D', b'R'), "addr"),
    (canon(b'W', b'D', b'T'), "width"),
    (canon(b'H', b'G', b'T'), "height"),
    (canon(b'P', b'T', b'H'), "pitch"),
    (canon(b'B', b'P', b'P'), "bpp"),
    (canon(b'C', b'M', b'P'), "compositor"),
    (canon(b'W', b'I', b'N'), "window"),
    (canon(b'P', b'X', b'M'), "pixmap"),
    (canon(b'S', b'T', b'M'), "streams"),
    (canon(b'C', b'M', b'B'), "composed_by"),
    (canon(b'W', b'C', b'R'), "window_created"),
    (canon(b'W', b'B', b'U'), "window_buffer_updated"),
    (canon(b'F', b'R', b'M'), "frame_ready"),
    (canon(b'I', b'N', b'P'), "driver_input"),
    (canon(b'D', b'S', b'P'), "driver_display"),
    (canon(b'S', b'T', b'R'), "driver_storage"),
    (canon(b'T', b'M', b'R'), "driver_timer"),
    (canon(b'O', b'T', b'H'), "driver_other"),
    (canon(b'D', b'E', b'V'), "device"),
    (canon(b'F', b'B', b'D'), "device.framebuffer"),
    (canon(b'K', b'B', b'D'), "device.keyboard"),
    (canon(b'M', b'D', b'V'), "device.mouse"),
    (canon(b'N', b'I', b'C'), "device.nic"),
    (canon(b'I', b'R', b'Q'), "irq.event"),
    (canon(b'D', b'M', b'A'), "dma.event"),
    (canon(b'I', b'Q', b'L'), "irq_line"),
    (canon(b'B', b'U', b'F'), "buffer"),
    (canon(b'B', b'Y', b'T'), "bytes"),
    (canon(b'D', b'O', b'N'), "done"),
    (canon(b'W', b'R', b'C'), "window_rect"),
    (canon(b'C', b'L', b'R'), "color"),
    (canon(b'V', b'S', b'B'), "visible"),
    (canon(b'B', b'M', b'P'), "bitmap"),
    (canon(b'D', b'R', b'T'), "dirty"),
    (canon(b'H', b'S', b'F'), "has_surface"),
    (canon(b'P', b'R', b'S'), "presents"),
    (canon(b'S', b'F', b'C'), "surface"),
    (canon(b'C', b'R', b'S'), "cursor"),
    (canon(b'S', b'B', b'F'), "buffer.shared"),
    (canon(b'Q', b'S', b'T'), "queue.state"),
    (canon(b'B', b'K', b'D'), "buffer.kind"),
    (canon(b'B', b'U', b'G'), "buffer.usage"),
    (canon(b'R', b'I', b'N'), "ring"),
    (canon(b'L', b'I', b'N'), "linear"),
    (canon(b'P', b'I', b'P'), "pipe"),
    (canon(b'S', b'R', b'F'), "surface"),
    (canon(b'R', b'X', b'R'), "rx_ring"),
    (canon(b'H', b'E', b'A'), "head"),
    (canon(b'T', b'A', b'I'), "tail"),
    (canon(b'H', b'D', b'T'), "has_data"),
    (canon(b'C', b'A', b'P'), "capacity"),
    (canon(b'X', b' ', b' '), "x"),
    (canon(b'Y', b' ', b' '), "y"),
    (canon(b'Z', b'I', b'N'), "z"),
    (canon(b'A', b'P', b'P'), "app"),
    (canon(b'T', b'Y', b'P'), "type"),
    (canon(b'V', b'E', b'R'), "version"),
];

pub fn symbol_from_str(name: &str) -> Option<Symbol> {
    SYMBOL_TABLE
        .iter()
        .find(|(_, label)| *label == name)
        .map(|(symbol, _)| *symbol)
}

pub fn symbol_name(symbol: Symbol) -> Option<&'static str> {
    SYMBOL_TABLE
        .iter()
        .find(|(sym, _)| *sym == symbol)
        .map(|(_, name)| *name)
}
