[package]
name = "demo_app"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
thing_abi = { path = "../../thing_abi" }
widget_checkbox = { path = "../../widgets/checkbox" }
uuid = { version = "=1.10", default-features = false, features = [
    "v5",
    "serde",
] }

[features]
default = []
std = ["userland/std"]
host = ["std"]

[[bin]]
name = "demo_app"
path = "src/main.rs"


[lib]
path = "src/lib.rs"
