[package]
name = "demo_app"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "=1.10", default-features = false, features = [
    "v5",
    "serde",
] }

[features]
default = []
std = ["userland/std"]
host = ["std"]

[[bin]]
name = "demo_app"
path = "src/main.rs"

[profile.release]
panic = "abort"

[lib]
path = "src/lib.rs"

[unstable]
build-std = ["core"]
