[workspace]
members = [
    "thing_abi",
    "thing_host",
    "kernel",
    "crates/kernel_std",
    "crates/thing_model",
    "userland",
    "compositor",
    "apps/*",
    "widgets/*",
    "drivers/*",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "=1.0.215", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_derive = { version = "1.0" }

[patch.crates-io]
ascii = { path = "third_party/ascii" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
