timeout: 0
/ThingOS
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/compositor
    module_path: boot():/boot/framebuffer_driver
    module_path: boot():/boot/keyboard_driver
    module_path: boot():/boot/mouse_driver
    module_path: boot():/boot/init
    module_path: boot():/boot/demo_app
    module_path: boot():/boot/task_list
    module_path: boot():/clouds.bmp
