[package]
name = "hello_from"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"

[build]
target = "x86_64-unknown-none"


[target.x86_64-unknown-none]
rustflags = [
  "-C", "link-arg=-Tlink.ld",
  "-C", "relocation-model=static"
]

[[bin]]
name = "hello_from"
path = "src/main.rs"

[unstable]
build-std = ["core"]

