[package]
name = "thing_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "=1.10", default-features = false, features = [
    "v5",
    "serde",
] }

[features]
default = []
std = ["userland/std"]
host = ["std"]
kernel_hosted = ["userland/kernel_hosted"]
disable_panic_handler = ["userland/disable_panic_handler"]

[[bin]]
name = "thing_viewer"
path = "src/main.rs"
