use alloc::vec::Vec;
use fontdue::{Font, FontSettings, Metrics};
use spin::Once;

// Include constants generated by build.rs
include!(concat!(env!("OUT_DIR"), "/fonts_includes.rs"));

pub struct FontManager {
    fonts: Vec<Font>,
    mono_font: Font,
}

static mut MANAGER: Option<FontManager> = None;
static ONCE: Once = Once::new();

pub fn font_manager() -> &'static FontManager {
    ONCE.call_once(|| unsafe {
        MANAGER = Some(FontManager::new());
    });
    unsafe { MANAGER.as_ref().unwrap() }
}

impl FontManager {
    pub fn new() -> Self {
        let settings = FontSettings::default();
        let fonts = alloc::vec![
            Font::from_bytes(NOTO_SANS, settings.clone()).unwrap(),
            Font::from_bytes(NOTO_SANS_SYMBOLS, settings.clone()).unwrap(),
            Font::from_bytes(NOTO_SANS_SYMBOLS2, settings.clone()).unwrap(),
        ];
        let mono_font = Font::from_bytes(HACK_REGULAR, settings).unwrap();
        Self { fonts, mono_font }
    }

    pub fn rasterize(&self, c: char, size: f32) -> (Metrics, Vec<u8>) {
        for font in &self.fonts {
            let idx = font.lookup_glyph_index(c);
            if idx != 0 {
                return font.rasterize(c, size);
            }
        }
        self.fonts[0].rasterize(c, size)
    }

    pub fn rasterize_mono(&self, c: char, size: f32) -> (Metrics, Vec<u8>) {
        let (metrics, bitmap) = self.mono_font.rasterize(c, size);
        if bitmap.is_empty() && !c.is_whitespace() {
             return self.fonts[0].rasterize(c, size);
        }
        (metrics, bitmap)
    }

    pub fn line_metrics(&self, size: f32) -> fontdue::LineMetrics {
        self.fonts[0].horizontal_line_metrics(size).unwrap_or_else(|| {
             // Fallback if missing? Should not happen for Noto Sans
             fontdue::LineMetrics {
                 ascent: size * 0.8,
                 descent: size * -0.2,
                 line_gap: 0.0,
                 new_line_size: size,
             }
        })
    }

    pub fn mono_line_metrics(&self, size: f32) -> fontdue::LineMetrics {
        // Force fallback metrics for Hack font to ensure consistent rendering
        fontdue::LineMetrics {
            ascent: size * 0.8,
            descent: size * -0.2,
            line_gap: 0.0,
            new_line_size: size,
        }
    }
}
