[package]
name = "compositor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
userland = { path = "../userland" }
uuid = { version = "1.10", default-features = false, features = [
  "v5",
  "serde",
] }
linked_list_allocator = { version = "0.10", optional = true }
app-clouds = { path = "../apps/clouds", optional = true }
app-hello = { path = "../apps/hello", optional = true }
app-clock = { path = "../apps/clock", optional = true }
app-graph-demo = { path = "../apps/graph_demo", optional = true }
app-keyboard-driver = { path = "../apps/keyboard_driver", optional = true }
unifont = { version = "1.1.0+data-15.1.05", default-features = false }

[profile.release]
panic = "abort"

[features]
default = []
demo-apps = [
  "linked_list_allocator",
  "app-clouds",
  "app-hello",
  "app-clock",
  "app-graph-demo",
  "app-keyboard-driver",
]

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tlink.ld", "-C", "relocation-model=static"]

[build-dependencies]
flate2 = "1.0"

[[bin]]
name = "compositor"
path = "src/main.rs"
required-features = ["demo-apps"]

[lib]
path = "src/lib.rs"

[unstable]
build-std = ["core"]
