[package]
name = "compositor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
userland = { path = "../userland" }
uuid = { version = "1.10", default-features = false, features = [
  "v5",
  "serde",
] }
unifont = { version = "1.1.0+data-15.1.05", default-features = false }

[build-dependencies]
flate2 = "1.0"

[features]
default = []
demo-apps = []
host = []

[[bin]]
name = "compositor"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[profile.release]
panic = "abort"
