[package]
name = "compositor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
userland = { path = "../userland" }
thing_host = { path = "../thing_host", optional = true }
uuid = { version = "=1.10", default-features = false, features = [
  "v5",
  "serde",
] }
unifont = { version = "1.1.0+data-15.1.05", default-features = false }
tiny_http = { version = "0.12", optional = true }

[build-dependencies]
flate2 = "1.0"

[features]
default = []
demo-apps = []
host = ["tiny_http", "thing_host", "userland/std"]

[[bin]]
name = "compositor"
path = "src/main.rs"

[[bin]]
name = "host_compositor"
path = "src/bin/host_compositor.rs"
required-features = ["host"]

[lib]
path = "src/lib.rs"

[profile.release]
panic = "abort"
