[package]
name = "widget_host"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "=1.10", default-features = false, features = [
    "v5",
    "serde",
] }
thing_abi = { path = "../../thing_abi" }
widget_launcher_entry = { path = "../launcher_entry" }
widget_scrollbar_thumb = { path = "../scrollbar_thumb" }
widget_toolbar = { path = "../toolbar" }
widget_button = { path = "../button" }
widget_listbox_default = { path = "../listbox_default" }
widget_notification_toast = { path = "../notification_toast" }
widget_notification_dialog = { path = "../notification_dialog" }
widget_image = { path = "../image" }
widget_checkbox = { path = "../checkbox" }
widget_radio_button = { path = "../radio_button" }
widget_top_status_bar = { path = "../top_status_bar" }
widget_status_widget = { path = "../status_widget" }
widget_thing_inspector = { path = "../thing_inspector" }
widget_graph_mini_viewer = { path = "../graph_mini_viewer" }

[features]
default = []
std = ["userland/std"]
host = ["std"]
disable_panic_handler = []

[[bin]]
name = "widget_host"
path = "src/main.rs"
