[package]
name = "app-clouds"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "1.10", default-features = false, features = ["v5", "serde"] }

[[bin]]
name = "clouds"
path = "src/lib.rs"

[profile.release]
panic = "abort"

[lib]
path = "src/lib.rs"

[unstable]
build-std = ["core"]
