[package]
name = "app-mouse-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "1.10", default-features = false, features = [
    "v5",
    "serde",
] }

[profile.release]
panic = "abort"

[build]
target = "x86_64-unknown-none"

[lib]
path = "src/lib.rs"

[unstable]
build-std = ["core"]
