[package]
name = "init"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
thing_abi = { path = "../../thing_abi" }

[target.'cfg(target_os = "none")'.dependencies]
# compositor = { path = "../../compositor", optional = true }

[features]
default = []
std = ["userland/std"]
kernel_hosted = ["userland/kernel_hosted"]
disable_panic_handler = ["userland/disable_panic_handler"]

[lib]
name = "init"
path = "src/lib.rs"

[[bin]]
name = "init"
path = "src/main.rs"
