[package]
name = "standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland", features = [
    "disable_panic_handler",
    "kernel_standalone",
] }
thing_abi = { path = "../../thing_abi" }
compositor = { path = "../../compositor" }
framebuffer-driver = { path = "../../drivers/framebuffer_driver", features = [
    "disable_panic_handler",
] }
keyboard-driver = { path = "../../drivers/keyboard_driver", features = [
    "disable_panic_handler",
] }
mouse-driver = { path = "../../drivers/mouse_driver", features = [
    "disable_panic_handler",
] }
widget_host = { path = "../../widgets/host", features = [
    "disable_panic_handler",
] }
text_editor = { path = "../../apps/text_editor" }
graph_viewer = { path = "../../apps/graph_viewer", features = [
    "disable_panic_handler",
] }

[features]
default = []
std = ["userland/std"]
