[package]
name = "widget_button"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
thing_abi = { path = "../../thing_abi" }
unifont = { version = "1.1.0", default-features = false }
svg-path-cst = "0.1"
embedded-graphics = "0.8"

[features]
default = []
std = ["userland/std"]
