[package]
name = "keyboard-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
userland = { path = "../../userland" }
uuid = { version = "=1.10", default-features = false, features = [
    "v5",
    "serde",
] }

[features]
default = []
std = ["userland/std"]
disable_panic_handler = []

[[bin]]
name = "keyboard_driver"
path = "src/main.rs"
