[package]
name = "userland"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
postcard = { version = "1.0.4", default-features = false, features = ["alloc"] }
uuid = { version = "=1.10", default-features = false, features = [
  "v5",
  "serde",
] }
linked_list_allocator = "0.10"
thing_abi = { path = "../thing_abi" }

[profile.release]
panic = "abort"
